### ISSUE TITLE
role: add SSL support

### ISSUE THREAD

**Issue by oleg-jukovec** [tarantool/http#199]
After the implementation of #35 we could add the TLS support into our role for Tarantool 3:

```yaml
server_name:
  listen: "localhost:3013"
  params:
    ssl_key_file: "path/to/key/file"
    ssl_cert_file: "path/to/key/file"
    ssl_ca_file: "path/to/key/file"
    ssl_ciphers: "cipher1:cipher2"
    ssl_password: "password"
    ssl_password_file: "path/to/ssl/password"
```
